# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 01:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('rh', models.CharField(max_length=5)),
                ('eps', models.CharField(max_length=255)),
                ('tipo', models.SmallIntegerField(choices=[(0, 'Prospecto'), (1, 'Aprendiz'), (2, 'Director')], default=0)),
                ('direccion', models.CharField(max_length=500)),
                ('acudientes', models.ManyToManyField(to='usuario.Acudiente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'verbose_name': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('tipo', models.SmallIntegerField(choices=[(0, 'Télefono fijo'), (1, 'Télefono móvil')], default=1)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Persona')),
            ],
        ),
    ]
